# Generated by Django 5.1.3 on 2024-11-29 14:51

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiryClub', models.CharField(choices=[('솔바람', '솔바람'), ('SoulLy', 'SoulLy'), ('운향', '운향'), ('운현극예술 연구회', '운현극예술 연구회'), ('카들레아', '카들레아'), ('F.O.R.K', 'F.O.R.K'), ('P.I.C.E', 'P.I.C.E'), ('M.O.D.s', 'M.O.D.s'), ('운산', '운산'), ('FC Flora', 'FC Flora'), ('하이클리어', '하이클리어'), ('BEAUTIFLY', 'BEAUTIFLY'), ('Win Hands Down', 'Win Hands Down'), ('ISSUE', 'ISSUE'), ('열음', '열음'), ('예운', '예운'), ('운지문학회', '운지문학회'), ('한빛', '한빛'), ('필름소피', '필름소피'), ('두들링', '두들링'), ('멋쟁이 사자처럼', '멋쟁이 사자처럼'), ('덕불', '덕불'), ('데레사', '데레사'), ('CCC', 'CCC'), ('RADIUS', 'RADIUS'), ('FM419', 'FM419'), ('자세히생각하라', '자세히생각하라'), ('이오', '이오'), ('덕성로타트랙', '덕성로타트랙'), ('KUSA', 'KUSA'), ('도담도담', '도담도담'), ('덕냥당', '덕냥당'), ('꽃신을신고', '꽃신을 신고')], max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=15)),
                ('student_id', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)])),
                ('nickname', models.CharField(max_length=50)),
                ('cp_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)])),
                ('image', models.ImageField(default='default.png', upload_to='upload_filepath')),
                ('is_manager', models.CharField(blank=True, choices=[('솔바람', '솔바람'), ('SoulLy', 'SoulLy'), ('운향', '운향'), ('운현극예술 연구회', '운현극예술 연구회'), ('카들레아', '카들레아'), ('F.O.R.K', 'F.O.R.K'), ('P.I.C.E', 'P.I.C.E'), ('M.O.D.s', 'M.O.D.s'), ('운산', '운산'), ('FC Flora', 'FC Flora'), ('하이클리어', '하이클리어'), ('BEAUTIFLY', 'BEAUTIFLY'), ('Win Hands Down', 'Win Hands Down'), ('ISSUE', 'ISSUE'), ('열음', '열음'), ('예운', '예운'), ('운지문학회', '운지문학회'), ('한빛', '한빛'), ('필름소피', '필름소피'), ('두들링', '두들링'), ('멋쟁이 사자처럼', '멋쟁이 사자처럼'), ('덕불', '덕불'), ('데레사', '데레사'), ('CCC', 'CCC'), ('RADIUS', 'RADIUS'), ('FM419', 'FM419'), ('자세히생각하라', '자세히생각하라'), ('이오', '이오'), ('덕성로타트랙', '덕성로타트랙'), ('KUSA', 'KUSA'), ('도담도담', '도담도담'), ('덕냥당', '덕냥당'), ('꽃신을신고', '꽃신을 신고')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
