# Generated by Django 5.1.3 on 2024-11-29 14:55

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_manager',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('솔바람', '솔바람'), ('SoulLy', 'SoulLy'), ('운향', '운향'), ('운현극예술 연구회', '운현극예술 연구회'), ('카들레아', '카들레아'), ('F.O.R.K', 'F.O.R.K'), ('P.I.C.E', 'P.I.C.E'), ('M.O.D.s', 'M.O.D.s'), ('운산', '운산'), ('FC Flora', 'FC Flora'), ('하이클리어', '하이클리어'), ('BEAUTIFLY', 'BEAUTIFLY'), ('Win Hands Down', 'Win Hands Down'), ('ISSUE', 'ISSUE'), ('열음', '열음'), ('예운', '예운'), ('운지문학회', '운지문학회'), ('한빛', '한빛'), ('필름소피', '필름소피'), ('두들링', '두들링'), ('멋쟁이 사자처럼', '멋쟁이 사자처럼'), ('덕불', '덕불'), ('데레사', '데레사'), ('CCC', 'CCC'), ('RADIUS', 'RADIUS'), ('FM419', 'FM419'), ('자세히생각하라', '자세히생각하라'), ('이오', '이오'), ('덕성로타트랙', '덕성로타트랙'), ('KUSA', 'KUSA'), ('도담도담', '도담도담'), ('덕냥당', '덕냥당'), ('꽃신을신고', '꽃신을 신고')], max_length=20),
        ),
    ]
