# Generated by Django 5.1.3 on 2024-12-03 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_author'),
        ('users', '0002_profile_club_recruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_news', to='news.news'),
        ),
    ]
