# Generated by Django 5.1.3 on 2024-11-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_manager',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
