# Generated by Django 5.1.3 on 2024-12-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('users', '0003_profile_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='club',
        ),
        migrations.AddField(
            model_name='profile',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='club_members', to='clubs.club'),
        ),
    ]
