# Generated by Django 5.1.3 on 2024-12-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='club',
            field=models.CharField(blank=True, choices=[('solbaram', '솔바람'), ('souly', 'SoulLy'), ('unhyang', '운향'), ('unhyun', '운현극예술 연구회'), ('kadleya', '카들레아'), ('fork', 'F.O.R.K'), ('pice', 'P.I.C.E'), ('mods', 'M.O.D.s'), ('unsan', '운산'), ('flora', 'FC Flora'), ('highclear', '하이클리어'), ('beautifly', 'BEAUTIFLY'), ('windown', 'Win Hands Down'), ('issue', 'ISSUE'), ('yeoleum', '열음'), ('yeun', '예운'), ('unjimoon', '운지문학회'), ('hanbit', '한빛'), ('filmsopi', '필름소피'), ('doodling', '두들링'), ('lion', '멋쟁이 사자처럼'), ('duckbool', '덕불'), ('theresa', '데레사'), ('ccc', 'CCC'), ('radius', 'RADIUS'), ('fm419', 'FM419'), ('jasang', '자세히생각하라'), ('io', '이오'), ('rotaract', '덕성로타트랙'), ('kusa', 'KUSA'), ('dodam', '도담도담'), ('deoknyang', '덕냥당'), ('flowersin', '꽃신을 신고')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_manager',
            field=models.CharField(blank=True, choices=[('solbaram', '솔바람'), ('souly', 'SoulLy'), ('unhyang', '운향'), ('unhyun', '운현극예술 연구회'), ('kadleya', '카들레아'), ('fork', 'F.O.R.K'), ('pice', 'P.I.C.E'), ('mods', 'M.O.D.s'), ('unsan', '운산'), ('flora', 'FC Flora'), ('highclear', '하이클리어'), ('beautifly', 'BEAUTIFLY'), ('windown', 'Win Hands Down'), ('issue', 'ISSUE'), ('yeoleum', '열음'), ('yeun', '예운'), ('unjimoon', '운지문학회'), ('hanbit', '한빛'), ('filmsopi', '필름소피'), ('doodling', '두들링'), ('lion', '멋쟁이 사자처럼'), ('duckbool', '덕불'), ('theresa', '데레사'), ('ccc', 'CCC'), ('radius', 'RADIUS'), ('fm419', 'FM419'), ('jasang', '자세히생각하라'), ('io', '이오'), ('rotaract', '덕성로타트랙'), ('kusa', 'KUSA'), ('dodam', '도담도담'), ('deoknyang', '덕냥당'), ('flowersin', '꽃신을 신고')], max_length=20),
        ),
    ]
