# Generated by Django 5.1.3 on 2024-12-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_club_alter_profile_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='club',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=50),
        ),
    ]
