# Generated by Django 5.1.3 on 2024-11-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('news_type', models.BooleanField(choices=[('다가올 소식', 'news_to_come'), ('지난 소식', 'Last_news')])),
            ],
        ),
    ]
