# Generated by Django 5.1.3 on 2024-11-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('news_type', models.CharField(choices=[('News_to_come', '다가올 소식'), ('Last_news', '지난 소식')], max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload_filepath')),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
