# Generated by Django 5.1.3 on 2024-11-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('News_to_come', '다가올 소식'), ('Last_news', '지난 소식')], max_length=15),
        ),
    ]
