# Generated by Django 5.1.3 on 2024-11-30 14:29

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('music', '공연ꞏ음악'), ('sports', '스포츠ꞏ레저'), ('volunteer', '사회ꞏ봉사'), ('art', '예술ꞏ창작'), ('study', '학술ꞏ탐구'), ('religion', '종교'), ('gender', '젠더ꞏ페미니즘'), ('it', 'IT'), ('culture', '문화ꞏ전통'), ('etc', '기타')], max_length=15)),
                ('frequency', models.CharField(max_length=20)),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[('mon', '월'), ('tue', '화'), ('wed', '수'), ('thu', '목'), ('fri', '금'), ('sat', '토'), ('sun', '일'), ('none', '해당 없음')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('fee_type', models.CharField(choices=[('yearly', '연간'), ('monthly', '월간'), ('one_time', '1회 납부')], max_length=15)),
                ('fee', models.PositiveIntegerField()),
                ('image', models.ImageField(default='default.png', upload_to='upload_filepath')),
                ('content', models.TextField()),
                ('likes_count', models.PositiveBigIntegerField(default=0)),
                ('contact', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'club'), name='unique_user_club')],
            },
        ),
    ]
