# Generated by Django 5.1.3 on 2024-12-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubuserrecord_delete_clubleaverecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuserrecord',
            name='leave_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
