# Generated by Django 5.0.7 on 2024-12-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_clubimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='image',
        ),
    ]
