# Generated by Django 5.1.3 on 2024-11-26 06:44

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRecruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('music', '공연ꞏ음악'), ('sports', '스포츠ꞏ레저'), ('volunteer', '사회ꞏ봉사'), ('art', '예술ꞏ창작'), ('study', '학술ꞏ탐구'), ('religion', '종교'), ('gender', '젠더ꞏ페미니즘'), ('it', 'IT'), ('culture', '문화ꞏ전통'), ('etc', '기타')], max_length=15)),
                ('style', models.CharField(choices=[('project', '프로젝트 및 대외 활동'), ('study', '학습 및 연구'), ('networking', '친목 및 네트워킹')], max_length=15)),
                ('frequency', models.CharField(max_length=20)),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[('mon', '월'), ('tue', '화'), ('wed', '수'), ('thu', '목'), ('fri', '금'), ('sat', '토'), ('sun', '일')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('fee_type', models.CharField(choices=[('yearly', '연간'), ('monthly', '월간'), ('one_time', '1회 납부')], max_length=15)),
                ('fee', models.PositiveIntegerField()),
                ('apply_method', models.CharField(max_length=20)),
                ('apply_process', models.CharField(max_length=20)),
                ('start_doc', models.DateField()),
                ('end_doc', models.DateField()),
                ('start_interview', models.DateField()),
                ('end_interview', models.DateField()),
                ('image', models.ImageField(default='default.png', upload_to='upload_filepath')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('is_temp', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
