# Generated by Django 5.1.3 on 2024-12-03 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRecruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_code', models.CharField(blank=True, max_length=20, null=True)),
                ('style', models.CharField(choices=[('project', '프로젝트 및 대외 활동'), ('study', '학습 및 연구'), ('networking', '친목 및 네트워킹')], max_length=15)),
                ('apply_method', models.CharField(choices=[('online', '온라인 신청'), ('email', '이메일 접수'), ('offline', '오프라인 신청')], max_length=15)),
                ('apply_process', models.CharField(choices=[('only_doc', '서류 전형'), ('doc_interview', '서류 및 면접 전형'), ('only_interview', '면접 전형'), ('none', '별도 전형 없음')], max_length=15)),
                ('start_doc', models.DateField()),
                ('end_doc', models.DateField()),
                ('start_interview', models.DateField()),
                ('end_interview', models.DateField()),
                ('image', models.ImageField(default='default.png', upload_to='upload_filepath')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('scraps_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.clubrecruit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'recruit'), name='unique_user_recruit')],
            },
        ),
    ]
