# Generated by Django 5.1.3 on 2024-11-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubrecruit',
            name='is_temp',
        ),
    ]
