# Generated by Django 5.1.3 on 2024-11-30 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('recruit', '0003_clubrecruit_scrap_count_recruitscrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubrecruit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clubrecruit',
            name='days',
        ),
        migrations.RemoveField(
            model_name='clubrecruit',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='clubrecruit',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='clubrecruit',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='clubrecruit',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='clubrecruit',
            name='location',
        ),
        migrations.RemoveField(
            model_name='clubrecruit',
            name='start_time',
        ),
        migrations.AddField(
            model_name='clubrecruit',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='clubrecruit',
            name='apply_method',
            field=models.CharField(choices=[('online', '온라인 신청'), ('email', '이메일 접수'), ('offline', '오프라인 신청')], max_length=15),
        ),
        migrations.AlterField(
            model_name='clubrecruit',
            name='apply_process',
            field=models.CharField(choices=[('only_doc', '서류 전형'), ('doc_interview', '서류 및 면접 전형'), ('only_interview', '면접 전형'), ('none', '별도 전형 없음')], max_length=15),
        ),
    ]
