# Generated by Django 5.1.3 on 2024-11-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_remove_clubrecruit_category_remove_clubrecruit_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubrecruit',
            old_name='scrap_count',
            new_name='scraps_count',
        ),
    ]
