# Generated by Django 5.1.4 on 2024-12-05 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_alter_clubrecruit_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='recruitscrap',
            name='unique_user_recruit',
        ),
        migrations.RemoveField(
            model_name='clubrecruit',
            name='author',
        ),
        migrations.AddField(
            model_name='clubrecruit',
            name='club_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clubrecruit',
            name='form_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='recruitscrap',
            constraint=models.UniqueConstraint(fields=('user', 'recruit'), name='unique_user_recruit_scrap'),
        ),
        migrations.AddField(
            model_name='recruitapply',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.clubrecruit'),
        ),
        migrations.AddField(
            model_name='recruitapply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='recruitapply',
            constraint=models.UniqueConstraint(fields=('user', 'recruit'), name='unique_user_recruit_apply'),
        ),
    ]
