# Generated by Django 5.0.7 on 2024-12-06 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_alter_clubrecruit_recruit_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubrecruit',
            name='image',
        ),
        migrations.CreateModel(
            name='ClubRecruitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recruit.clubrecruit')),
            ],
        ),
    ]
