# Generated by Django 5.0.7 on 2024-12-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_remove_clubrecruit_image_clubrecruitimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubrecruitimage',
            old_name='club',
            new_name='clubrecruit',
        ),
    ]
