# Generated by Django 5.0.7 on 2024-12-14 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0009_rename_club_clubrecruitimage_clubrecruit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrecruit',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recruit_author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
